FROM node:20-bookworm-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    imagemagick \
    libheif-examples \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml || true

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

CMD ["npm", "run", "dev"]