FROM node:20-alpine

# Installation de FFmpeg pour le développement
RUN apk update && apk add --no-cache ffmpeg libc6-compat

WORKDIR /app

# Installation des dépendances
COPY package.json package-lock.json ./
RUN npm install

# (Le reste du code sera synchronisé dynamiquement via docker-compose)

# Lancement de Next.js en mode développement
CMD ["npm", "run", "dev"]